---
 - name: "update apt packages."
   become: true
   apt:
     update_cache: yes
     cache_valid_time: 55555


 - name: "upgrade packages"
   become: true
   apt:
     upgrade: yes
     

 - name: "remove those dependencies that were installed with applications and are no longer used by anything else on the system."
   become: true
   apt:
     autoremove: yes


 - name: "install npm , nodejs"
   become: yes
   apt:
     name: ["npm", "nodejs"]
     state: latest
     update_cache: yes


 - name: "install pm2"
   become: yes
   npm:
     name: pm2
     global: yes
     production: yes
     state: present